// Synthetic engineer roster — strengths & skillsets for capacity planning demos.
// Illustrative only; no real PII.

import {
  TEAMS,
  PLANNING_GROUPS,
  TALENT_PROFILE,
} from "../lib/types.mjs";

export const ENGINEERS = [
  {
    id: "ENG-001",
    name: "Alex Chen",
    team: TEAMS.PAYMENTS_ENG,
    planningGroup: PLANNING_GROUPS.PAYMENTS,
    role: "Staff Engineer",
    talentProfile: TALENT_PROFILE.STAFF_PLUS,
    strength: "Real-time payments pricing and checkout throughput",
    skillset: ["pricing APIs", "payments", "low-latency", "transaction routing"],
  },
  {
    id: "ENG-002",
    name: "Jordan Blake",
    team: TEAMS.PAYMENTS_ENG,
    planningGroup: PLANNING_GROUPS.PAYMENTS,
    role: "Senior Engineer",
    talentProfile: TALENT_PROFILE.SPECIALIST,
    strength: "Partner integrations and merchant onboarding flows",
    skillset: ["partner APIs", "onboarding", "B2B workflows", "integrations"],
  },
  {
    id: "ENG-003",
    name: "Sam Okonkwo",
    team: TEAMS.CONSUMER_PRODUCT,
    planningGroup: PLANNING_GROUPS.GROWTH,
    role: "Product Engineer",
    talentProfile: TALENT_PROFILE.ANY,
    strength: "Consumer growth funnels and marketplace acquisition",
    skillset: ["growth experiments", "conversion", "A/B testing", "marketplace"],
  },
  {
    id: "ENG-004",
    name: "Riley Martinez",
    team: TEAMS.CONSUMER_PRODUCT,
    planningGroup: PLANNING_GROUPS.GROWTH,
    role: "Senior Engineer",
    talentProfile: TALENT_PROFILE.SPECIALIST,
    strength: "Seller portals, e-sign, and marketplace onboarding UX",
    skillset: ["portals", "e-sign", "marketplace", "React", "accessibility"],
  },
  {
    id: "ENG-005",
    name: "Jesse Park",
    team: TEAMS.CORE_PLATFORM,
    planningGroup: PLANNING_GROUPS.CORE_PLATFORM,
    role: "Staff Engineer",
    talentProfile: TALENT_PROFILE.STAFF_PLUS,
    strength: "Account management workflows and billing reliability",
    skillset: ["account services", "billing", "subscriptions", "SLO design"],
  },
  {
    id: "ENG-006",
    name: "Casey Nguyen",
    team: TEAMS.CORE_PLATFORM,
    planningGroup: PLANNING_GROUPS.CORE_PLATFORM,
    role: "Engineer",
    talentProfile: TALENT_PROFILE.ANY,
    strength: "Self-serve customer tools and CSAT-sensitive surfaces",
    skillset: ["customer portal", "customer service", "forms", "mobile web"],
  },
  {
    id: "ENG-007",
    name: "Taylor Brooks",
    team: TEAMS.DATA_ANALYTICS,
    planningGroup: PLANNING_GROUPS.DEVELOPER_PLATFORM,
    role: "Senior Data Engineer",
    talentProfile: TALENT_PROFILE.SPECIALIST,
    strength: "Portfolio extract pipelines and cross-system reconciliation",
    skillset: ["ETL", "STRATA", "Snowflake", "reconciliation", "data quality"],
  },
  {
    id: "ENG-008",
    name: "Quinn Foster",
    team: TEAMS.DATA_ANALYTICS,
    planningGroup: PLANNING_GROUPS.DEVELOPER_PLATFORM,
    role: "Platform Engineer",
    talentProfile: TALENT_PROFILE.ANY,
    strength: "Shared platform services and internal enabler work",
    skillset: ["platform core", "observability", "CI/CD", "internal tools"],
  },
  {
    id: "ENG-009",
    name: "Avery Kim",
    team: TEAMS.TRUST_SAFETY_ENG,
    planningGroup: PLANNING_GROUPS.TRUST_SAFETY,
    role: "Senior Engineer",
    talentProfile: TALENT_PROFILE.SPECIALIST,
    strength: "Policy mandates and audit-grade control implementations",
    skillset: ["compliance", "controls", "audit trails", "risk registers"],
  },
  {
    id: "ENG-010",
    name: "Drew Ellison",
    team: TEAMS.TRUST_SAFETY_ENG,
    planningGroup: PLANNING_GROUPS.TRUST_SAFETY,
    role: "Engineer",
    talentProfile: TALENT_PROFILE.ANY,
    strength: "Policy automation and access-governance workflows",
    skillset: ["policy engines", "access control", "governance workflows", "documentation"],
  },
];