// LOOPER — SYNTHETIC demo portfolio (Appendix A rubric, full).
//
// Illustrative only. No real names, no confidential data — made-up initiatives
// chosen to show the engine doing what a product operating model actually needs:
// catching duplicate builds, ranking by time-value-correct NPV, surfacing
// found-money, pinning mandates, parking stale work, and refusing the napkin.
//
// Required scenarios baked in:
//   • a 3-item DUPLICATE CLUSTER  (INIT-009/010/011 — "pricing calculator")
//   • a MANDATE / policy item     (INIT-003 — auto-pins to Now)
//   • an "insurance portal" FOUND-MONEY item (INIT-001 — high rev, low effort)
//   • a STALE WATCHLIST item      (INIT-012 — state: Watchlist)
//   • the TIME-VALUE PAIR         (INIT-006 early-effective vs INIT-007 late-
//     effective, otherwise identical cost-saves — early must rank above late)
//   • a spread of all 5 value types
//   • a NAPKIN idea that is refused at intake (INIT-013 — no structure/evidence)
//
// Dates use 2026-01-01 as the horizon start (see lib/score.mjs horizonStart).

import {
  VALUE_TYPES,
  TALENT_PROFILE,
  CONFIDENCE,
  BUDGET_CYCLE,
  BUSINESS_IMPACT,
  STATES,
  LEVELS,
  PLANNING_GROUPS,
  TEAMS,
  PRODUCTS,
} from "../lib/types.mjs";
import { normalizeBatch } from "../lib/hierarchy.mjs";

const BASE_INITIATIVES = [
  // ── FOUND MONEY: the insurance portal that came out of nowhere ────────────
  {
    id: "INIT-001",
    title: "Insurance Agent Portal",
    description:
      "Net-new self-serve portal that signs and onboards insurance agents into the marketplace. High-margin revenue line, small surface area — found money.",
    area: "Growth",
    sponsor: "Strategy",
    outcome: "insurance agent marketplace portal",
    valueType: VALUE_TYPES.REVENUE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.CONSUMER,
    reach: { value: 18000, unit: "agents", source: "Partnerships TAM model 2026-Q1" },
    revenueImpact: 7_200_000,
    cogs: 0.18,
    ongoingTCO: 140_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 8,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "Partnerships TAM model 2026-Q1",
      revenue: "Strategy revenue memo INS-2026-014",
      tco: "Cloud cost quote REF-Q1-883",
    },
    state: STATES.SUBMITTED,
  },

  // ── REVENUE: partner pricing service (bigger build, real upside) ──────────
  {
    id: "INIT-002",
    title: "Partner Pricing Service",
    description:
      "Real-time pricing for the partner channel to win transaction volume from competitors with faster, sharper quotes.",
    area: "Payments",
    sponsor: "Payments",
    outcome: "partner real-time transaction pricing",
    valueType: VALUE_TYPES.REVENUE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PARTNER,
    reach: { value: 42000, unit: "items", source: "Partner volume FY25 actuals" },
    revenueImpact: 5_400_000,
    cogs: 0.22,
    ongoingTCO: 220_000,
    budgetCyclePosition: BUDGET_CYCLE.CROSSES_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 22,
    talentProfile: TALENT_PROFILE.SPECIALIST,
    dependsOn: [],
    evidence: {
      reach: "Partner volume FY25 actuals",
      revenue: "Revenue uplift study REV-2026-07",
      tco: "Infra estimate REF-Q1-901",
    },
    state: STATES.SUBMITTED,
  },

  // ── MANDATE / policy: must-do, auto-pins to Now ───────────────────────────
  {
    id: "INIT-003",
    title: "Data Consent Disclosure Update",
    description:
      "Mandatory consent-disclosure change for new customer sign-ups. Non-compliance is a hard stop — funded regardless of score.",
    area: "Trust & Safety",
    sponsor: "Policy",
    outcome: "customer consent disclosure compliance",
    valueType: VALUE_TYPES.RISK,
    mandate: true,
    mandateCitation: "Data Consent Policy DCP-2026-11 (eff. 2026-09-01)",
    businessImpact: BUSINESS_IMPACT.CONSUMER,
    reach: { value: 31000, unit: "items", source: "New sign-up volume FY25" },
    riskReduction: 4_000_000,
    pRisk: 0.6,
    ongoingTCO: 20_000,
    budgetCyclePosition: BUDGET_CYCLE.POST_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.HIGH,
    effortTeamWeeks: 6,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      mandate: "Data Consent Policy DCP-2026-11",
      reach: "New sign-up volume FY25",
      riskReduction: "Risk register R-2026-1180",
      tco: "Compliance run-cost note CMP-12",
    },
    state: STATES.SUBMITTED,
  },

  // ── SERVICE: customer self-service billing (customer-impact led) ──────────
  {
    id: "INIT-004",
    title: "Customer Billing Self-Service",
    description:
      "Lets customers manage and schedule payments without calling support. Lifts CSAT and deflects call volume.",
    area: "Core Platform",
    sponsor: "Core Platform",
    outcome: "self-service customer billing management",
    valueType: VALUE_TYPES.SERVICE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 260000, unit: "customers", source: "Account portfolio 2026" },
    customerImpact: 900_000,
    costSaveAnnual: 480_000,
    savingsEffectiveDate: "2026-06-01",
    ongoingTCO: 90_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.HIGH,
    effortTeamWeeks: 14,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "Account portfolio 2026",
      customerImpact: "CSAT-to-retention model ACC-2026-03",
      costSave: "Call-deflection model ACC-2026-04",
      tco: "Infra estimate REF-Q1-915",
    },
    state: STATES.SUBMITTED,
  },

  // ── ENABLER: sprint reporting automation (quick internal win) ─────────────
  {
    id: "INIT-005",
    title: "Auditable Sprint Reporting",
    description:
      "Generates sprint/release reporting straight from Jira + git — kills hours of manual status assembly and makes the record auditable.",
    area: "Portfolio Ops",
    sponsor: "Portfolio Ops",
    outcome: "auditable sprint reporting from jira and git",
    valueType: VALUE_TYPES.ENABLER,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 320, unit: "engineers", source: "HC roster 2026-Q1" },
    costSaveAnnual: 360_000,
    savingsEffectiveDate: "2026-03-01",
    ongoingTCO: 15_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.HIGH,
    effortTeamWeeks: 4,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "HC roster 2026-Q1",
      costSave: "Time-study OPS-2026-02",
      tco: "Tooling quote OPS-Q1-21",
    },
    state: STATES.SUBMITTED,
  },

  // ── TIME-VALUE PAIR — identical cost-saves, different effective dates ──────
  // INIT-006 goes live EARLY (month 2). INIT-007 goes live LATE (month 11). Same
  // $1.2M/yr save, same everything else → INIT-006 MUST rank above INIT-007.
  {
    id: "INIT-006",
    title: "Certificate Rotation Automation",
    description:
      "Automates certificate rotation across the estate. Rollout completes in month 2, so the savings start realizing almost immediately.",
    area: "Resiliency",
    sponsor: "Core Ops",
    outcome: "automated tls certificate rotation estate",
    valueType: VALUE_TYPES.ENABLER,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 320, unit: "engineers", source: "HC roster 2026-Q1" },
    costSaveAnnual: 1_200_000,
    savingsEffectiveDate: "2026-02-01", // EARLY
    ongoingTCO: 30_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.HIGH,
    effortTeamWeeks: 5,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "HC roster 2026-Q1",
      costSave: "Toil-reduction model OPS-2026-09",
      tco: "Tooling quote OPS-Q1-30",
    },
    state: STATES.SUBMITTED,
  },
  {
    id: "INIT-007",
    title: "Secrets Vault Migration",
    description:
      "Same recurring cost-save as the cert-rotation work, but a staffing constraint pushes the rollout to month 11 — the savings barely land inside Year 1. Identical numbers, late effective date: the time-value control.",
    area: "Resiliency",
    sponsor: "Core Ops",
    outcome: "centralized secrets vault migration",
    valueType: VALUE_TYPES.ENABLER,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 320, unit: "engineers", source: "HC roster 2026-Q1" },
    costSaveAnnual: 1_200_000,
    savingsEffectiveDate: "2026-11-01", // LATE
    ongoingTCO: 30_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.HIGH,
    effortTeamWeeks: 5,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "HC roster 2026-Q1",
      costSave: "Toil-reduction model OPS-2026-09",
      tco: "Tooling quote OPS-Q1-30",
    },
    state: STATES.SUBMITTED,
  },

  // ── OPTIONALITY: platform decommission (strategic, expensive) ─────────────
  {
    id: "INIT-008",
    title: "Legacy Platform Decommission",
    description:
      "Retires the legacy platform, unlocking faster delivery everywhere downstream. Strategic optionality more than near-term dollars.",
    area: "Platform Ops",
    sponsor: "Portfolio Ops",
    outcome: "decommission the legacy platform",
    valueType: VALUE_TYPES.OPTIONALITY,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PARTNER,
    reach: { value: 320, unit: "engineers", source: "HC roster 2026-Q1" },
    costSaveAnnual: 700_000,
    savingsEffectiveDate: "2027-01-01",
    costAvoid: 1_500_000,
    pAvoid: 0.5,
    ongoingTCO: 60_000,
    budgetCyclePosition: BUDGET_CYCLE.CROSSES_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 30,
    talentProfile: TALENT_PROFILE.STAFF_PLUS,
    dependsOn: [],
    evidence: {
      reach: "HC roster 2026-Q1",
      costSave: "Decommission savings model REF-2026-11",
      costAvoid: "Counterfactual: legacy EOL support quote REF-2026-12",
      tco: "Residual run-cost REF-Q1-940",
    },
    state: STATES.SUBMITTED,
  },

  // ── THE THREE-CALCULATOR PROBLEM (same outcome, three areas) ──────────────
  {
    id: "INIT-009",
    title: "Customer Pricing Calculator — Sales",
    description: "Sales wants a customer-facing pricing calculator.",
    area: "Sales",
    sponsor: "Sales",
    outcome: "pricing calculator",
    valueType: VALUE_TYPES.SERVICE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.CONSUMER,
    reach: { value: 120000, unit: "customers", source: "Sales web traffic 2025" },
    revenueImpact: 600_000,
    cogs: 0.2,
    customerImpact: 120_000,
    ongoingTCO: 25_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 6,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "Sales web traffic 2025",
      revenue: "Lead-conversion model SAL-2026-01",
      customerImpact: "CSAT proxy SAL-2026-02",
      tco: "Tooling quote SAL-Q1-04",
    },
    state: STATES.SUBMITTED,
  },
  {
    id: "INIT-010",
    title: "Customer Pricing Calculator — Accounts",
    description: "The accounts team wants the same pricing calculator for its portal.",
    area: "Core Platform",
    sponsor: "Core Platform",
    outcome: "pricing calculator",
    valueType: VALUE_TYPES.SERVICE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 60000, unit: "customers", source: "Account portal traffic 2025" },
    customerImpact: 80_000,
    ongoingTCO: 25_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 6,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "Account portal traffic 2025",
      customerImpact: "CSAT proxy ACC-2026-08",
      tco: "Tooling quote ACC-Q1-09",
    },
    state: STATES.SUBMITTED,
  },
  {
    id: "INIT-011",
    title: "Customer Pricing Calculator — Partners",
    description: "The partner team wants the same pricing calculator for partners.",
    area: "Payments",
    sponsor: "Payments",
    outcome: "pricing calculator",
    valueType: VALUE_TYPES.SERVICE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PARTNER,
    reach: { value: 12000, unit: "partners", source: "Partner count 2025" },
    customerImpact: 40_000,
    ongoingTCO: 25_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.LOW,
    effortTeamWeeks: 6,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "Partner count 2025",
      customerImpact: "CSAT proxy PAR-2026-02",
      tco: "Tooling quote PAR-Q1-03",
    },
    state: STATES.SUBMITTED,
  },

  // ── STALE WATCHLIST: parked last quarter, no movement ─────────────────────
  {
    id: "INIT-012",
    title: "Internal Wiki Search Revamp",
    description:
      "A nice-to-have search refresh that was parked on the watchlist two quarters ago and never picked back up.",
    area: "Internal Tools",
    sponsor: "Eng Enablement",
    outcome: "internal wiki search relevance revamp",
    valueType: VALUE_TYPES.ENABLER,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PLATFORM,
    reach: { value: 320, unit: "engineers", source: "HC roster 2026-Q1" },
    costSaveAnnual: 60_000,
    savingsEffectiveDate: "2026-09-01",
    ongoingTCO: 10_000,
    budgetCyclePosition: BUDGET_CYCLE.POST_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.LOW,
    effortTeamWeeks: 7,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: [],
    evidence: {
      reach: "HC roster 2026-Q1",
      costSave: "Search time-study ENB-2025-19",
      tco: "Tooling quote ENB-Q3-44",
    },
    state: STATES.WATCHLIST, // <- stale, stays on Watchlist
  },

  // ── NAPKIN IDEA — refused at intake (no structure, no evidence) ───────────
  {
    id: "INIT-013",
    title: "Big AI Thing (no details yet)",
    description: "An influential VP wants 'an AI thing'. No rubric, no sources.",
    area: "Sales",
    sponsor: "An Influential VP",
    outcome: "unspecified ai initiative",
    // intentionally missing: valueType, reach, confidences, effort, evidence
    // → REFUSED by intake (structure + evidence both fail)
  },

  // ── HIERARCHY: Epic + UserStory under INIT-001 (3-level stack rank demo) ────
  {
    id: "INIT-001-EPIC",
    title: "Agent Onboarding Flow",
    description: "Epic: self-serve sign-up and credentialing for insurance agents.",
    area: "Growth",
    sponsor: "Strategy",
    outcome: "insurance agent self-serve onboarding",
    valueType: VALUE_TYPES.REVENUE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.CONSUMER,
    level: LEVELS.EPIC,
    parentId: "INIT-001",
    planningGroup: PLANNING_GROUPS.GROWTH,
    team: TEAMS.CONSUMER_PRODUCT,
    product: PRODUCTS.MARKETPLACE,
    reach: { value: 12000, unit: "agents", source: "Partnerships funnel 2026-Q1" },
    revenueImpact: 2_400_000,
    cogs: 0.18,
    ongoingTCO: 45_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 5,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: ["INIT-001"],
    evidence: {
      reach: "Partnerships funnel 2026-Q1",
      revenue: "Strategy revenue memo INS-2026-014",
      tco: "Cloud cost quote REF-Q1-883",
    },
    state: STATES.SUBMITTED,
  },
  {
    id: "INIT-001-STORY",
    title: "Agent E-Sign Capture",
    description: "User story: capture e-signatures during agent onboarding.",
    area: "Growth",
    sponsor: "Strategy",
    outcome: "agent e-sign capture during onboarding",
    valueType: VALUE_TYPES.REVENUE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.CONSUMER,
    level: LEVELS.USER_STORY,
    parentId: "INIT-001-EPIC",
    planningGroup: PLANNING_GROUPS.GROWTH,
    team: TEAMS.CONSUMER_PRODUCT,
    product: PRODUCTS.MARKETPLACE,
    reach: { value: 12000, unit: "agents", source: "Partnerships funnel 2026-Q1" },
    revenueImpact: 600_000,
    cogs: 0.1,
    ongoingTCO: 8_000,
    budgetCyclePosition: BUDGET_CYCLE.PRE_LOCK,
    deliveryConfidence: CONFIDENCE.HIGH,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 2,
    talentProfile: TALENT_PROFILE.ANY,
    dependsOn: ["INIT-001-EPIC"],
    evidence: {
      reach: "Partnerships funnel 2026-Q1",
      revenue: "Strategy revenue memo INS-2026-014",
      tco: "Cloud cost quote REF-Q1-883",
    },
    state: STATES.SUBMITTED,
  },
  {
    id: "INIT-002-EPIC",
    title: "Partner Rate API",
    description: "Epic: real-time rate API for the partner channel.",
    area: "Payments",
    sponsor: "Payments",
    outcome: "partner rate api for the channel",
    valueType: VALUE_TYPES.REVENUE,
    mandate: false,
    businessImpact: BUSINESS_IMPACT.PARTNER,
    level: LEVELS.EPIC,
    parentId: "INIT-002",
    planningGroup: PLANNING_GROUPS.PAYMENTS,
    team: TEAMS.PAYMENTS_ENG,
    product: PRODUCTS.CHECKOUT,
    reach: { value: 18000, unit: "items", source: "Partner channel volume FY25" },
    revenueImpact: 1_800_000,
    cogs: 0.22,
    ongoingTCO: 60_000,
    budgetCyclePosition: BUDGET_CYCLE.CROSSES_LOCK,
    deliveryConfidence: CONFIDENCE.MEDIUM,
    valueConfidence: CONFIDENCE.MEDIUM,
    effortTeamWeeks: 10,
    talentProfile: TALENT_PROFILE.SPECIALIST,
    dependsOn: ["INIT-002"],
    evidence: {
      reach: "Partner channel volume FY25",
      revenue: "Partner revenue model PAR-2026-03",
      tco: "Infra quote PAR-Q1-12",
    },
    state: STATES.SUBMITTED,
  },
];

/** Full portfolio with LOOPER taxonomy defaults applied. */
export const INITIATIVES = normalizeBatch(BASE_INITIATIVES);
